name: GitHub Actions Test
# run-name: ${{ github.actor }} workflow test
on:
    push:
        branches: [main, stage]
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm triggered by  a ${{ github.event_name }} event."
      - run: echo "This is my checkout reposioty ${{ github.repository }}."
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: echo "Repository is now cloned, see my list of files:"
      - name: List files
        run: |
          ls ${{ github.workspace}}
      - name: login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: add azure Az extention
        run: az extension add --name ml

      - name: List directory contents
        run: ls -lah
    # conditional for main to enable train on small subset of the dataset
      - name: Test train
        if: github.ref == 'refs/heads/main'
        run: |
          # on push trigger to stage branch, run unnitest
          az ml job create --file ./production/job.yaml --resource-group Test1 --workspace-name test1

    # submit model for trainig and model training with full dataset
      - name: Run unit testing
        if: github.ref == 'refs/heads/stage'
        run: |
         # on pull trigger to main branch, run model
         az ml job create --file ./production/job1.yaml --resource-group com774_cw2 --workspace-name com774_cw2

        
      
